import logging

from .util import Attributes


log_level = Attributes({
    'CRIT': logging.CRITICAL,
    'crit': logging.CRITICAL,
    'ERROR': logging.ERROR,
    'error': logging.ERROR,
    'WARN': logging.WARN,
    'warn': logging.WARN,
    'INFO': logging.INFO,
    'info': logging.INFO,
    'DEBUG': logging.DEBUG,
    'debug': logging.DEBUG,
    'NOTSET': logging.NOTSET,
    'noset': logging.NOTSET,
})

err_codes = Attributes({
    'success': 0,
    'error_login_first': 1000,
    'error_initialize_fail': 1001,
    'error_account_not_exist': 1002,
    'error_account_market_not_match': 1003,
    'error_period_out_of_range': 1004,
    'error_flag_out_of_range': 1005,
    'error_buysell_out_of_range': 1006,
    'error_order_server_invalid': 1007,
    'error_permission_denied': 1008,
    'error_trade_typr_out_of_range': 1009,
    'error_day_trade_out_of_range': 1010,
    'error_order_sign_invalid': 1011,
    'error_new_close_out_of_range': 1012,
    'error_product_invalid': 1013,
    'error_qty_invalid': 1014,
    'error_daytrade_denied': 1015,
    'error_spcial_trade_type_invalid': 1016,
    'error_price_invalid': 1017,
    'error_index_out_of_range': 1018,
    'error_query_in_processing': 1019,
    'error_login_invalid': 1020,
    'error_register_callback': 1021,
    'error_function_permission_denied': 1022,
    'error_market_out_of_range': 1023,
    'error_permission_timeout': 1024,
    'error_foreignstock_price_out_of_range': 1025,
    'error_foreignstock_undefine_cointype': 1026,
    'error_foreignstock_same_coinstype': 1027,
    'error_foreignstock_sale_should_original_coin': 1028,
    'error_foreignstock_trade_unit_invalid': 1029,
    'error_foreignstock_stockno_invalid': 1030,
    'error_foreignstock_accounttype_invalid': 1031,
    'error_foreignstock_initialize_fail': 1032,
    'error_ts_initialize_fail': 1033,
    'error_oversea_trade_product_fail': 1034,
    'error_oversea_trade_data_not_complete': 1035,
    'error_cert_verify_cn_invalid': 1036,
    'error_cert_verify_server_reject': 1037,
    'error_cert_not_verified': 1038,
    'error_oversea_account_not_exist': 1039,
    'error_order_lock': 1040,
    'error_server_not_connected': 1041,
    'error_oversea_kline_data_type_not_found': 1042,
    'error_strikeprice_invalid': 1043,
    'error_callput_invalid': 1044,
    'error_cert_not_found': 1045,
    'error_reserved_out_of_range': 1046,
    'error_smart_trade_order_server_invalid': 1047,
    'error_cancel_order_smartkey_invalid': 1048,
    'error_oversea_future_spread_order': 1049,
    'error_mit_order_exclude_spread_product': 1050,
    'error_sgx_api_order_seqno_confilict': 1051,
    'error_oversea_future_spread_order_no_daytrade': 1052,
    'error_sgx_api_logon_fail': 1053,
    'error_mit_order_must_give_trigger_price': 1054,
    'error_mit_order_must_give_deal_price': 1056,
    'error_withdraw_without_password': 1057,
    'error_withdrawinout_type_out_of_range': 1058,
    'error_currency_out_of_range': 1059,
    'error_ap_gw_server_invalid': 1060,
    'error_strategy_order_buysell_invalid': 1061,
    'error_strategy_order_smartkey_type_invalid': 1062,
    'error_strategy_order_market_type_invalid': 1063,
    'error_strategy_order_trade_type_invalid': 1064,
    'error_correct_price_only_lmt_range': 1065,
    'error_prohibit_emerging_stock_in_continuous_trading': 1066,
    'error_special_trade_type_out_of_range': 1067,
    'error_special_trade_type_is_marketprice_and_orderprice_should_be_zero': 1068,
    'error_market_type_invalid': 1069,
    'error_prohibit_oddlots_afterhours_continuous_trading': 1070,
    'error_correct_price_only_lmt_range': 1071,
    'error_sgx_dma_is_not_allow_correctprice_bybookno': 1072,
    'error_sgx_api_order_seqno_error': 1073,
    'error_query_agreement': 1074,
    'error_all_agreement_signed': 1075,
    'error_profitlossgwquery_date_invalid': 1076,
    'error_profitlossgwquery_bookno_is_invalid': 1077,
    'error_profitlossgwquery_seqno_is_invalid': 1078,
    'error_login_without_password': 1079,
    'error_login_without_loginid': 1080,
    'error_login_without_setquote': 1081,
    'error_there_is_no_oversea_future_account': 1082,
    'warning_of_com_data_missing': 2001,
    'warning_ts_ready': 2002,
    'warning_login_already': 2003,
    'warning_login_special_already': 2004,
    'warning_cert_verified_already': 2005,
    'warning_order_did_not_locked': 2006,
    'warning_oo_com_quotedata_missing': 2007,
    'warning_oo_com_orderdata_missing': 2008,
    'warning_sign_ts_smarttrade_risk_noitice_first': 2009,
    'warning_sign_tf_smarttrade_risk_noitice_first': 2010,
    'warning_no_function_in_continuous_trading': 2011,
    'warning_osquotecenter_is_not_exist': 2012,
    'warning_initialize_osquotecenter_connection_fail': 2013,
    'warning_initialize_osquotecenter_oo_connection_fail': 2014,
    'warning_download_of_com_data_is_timeout': 2015,
    'warning_download_oo_com_data_is_timeout': 2016,
    'warning_register_replylib_onreplymessage_first': 2017,
    'warning_sign_stock_or_future_api_agreement_first': 2018,
    'warning_sign_future_api_agreement_first': 2019,
    'subject_connection_connected': 3001,
    'subject_connection_disconnect': 3002,
    'subject_connection_stocks_ready': 3003,
    'subject_connection_clear': 3004,
    'subject_connection_reconnect': 3005,
    'subject_quote_page_exceed': 3006,
    'subject_quote_page_incorrect': 3007,
    'subject_tick_page_exceed': 3008,
    'subject_tick_page_incorrect': 3009,
    'subject_tick_stock_not_found': 3010,
    'subject_best5_data_not_found': 3011,
    'subject_quoterequest_not_found': 3012,
    'subject_server_time_not_found': 3013,
    'subject_all_market_ok': 3015,
    'subject_market_info_ready': 3016,
    'subject_catalog_list_ready': 3017,
    'subject_initializestocks': 3018,
    'subject_macd_data_not_found': 3019,
    'subject_booltunel_data_not_found': 3020,
    'subject_connection_fail': 3021,
    'subject_connection_solclientapi_fail': 3022,
    'subject_stockno_is_invalid': 3023,
    'subject_market_no_is_out_of_range': 3024,
    'subject_cant_accept_spread_stockno': 3025,
    'subject_connection_sgx_api_ready': 3026,
    'subject_tick_limit_exceed': 3027,
    'subject_quote_limit_exceed_in_one_page': 3028,
    'subject_quote_string_exist_null': 3029,
    'subject_no_quote_subscribe': 3030,
    'subject_no_related_market_stocks': 3031,
    'kline_data_type_not_found': 4001,
    'error_login_wrong_password': 151,
    'error_login_wrong_password_over_limit': 152,
    'error_login_wrong_id': 153,
    'error_change_password_in_first_time': 155,
    'fail': 9999,
})

market_type = Attributes({
    'listed_at_exchange': 0,
    'listed_at_over_the_counter': 1,
    'feature': 2,
    'option': 3,
    'listed_at_emerging': 4,
})


candlestick_type = Attributes({
    'minute': 0,
    'day': 4,
    'week': 5,
    'month': 6,
})


candlestick_output_type = Attributes({
    'old': 0,
    'new': 1,
})

candlestick_trade_session = Attributes({
    'all_day': 0,
    'daylight': 1,
})

subscribe_type = Attributes({
    'tick': 'tick',
    'candlestick': 'candlestick',
    'orderbook': 'orderbook',
    'quotation': 'quotation',
    'all': ''
})
